name: auto-release-milestone
on:
  milestone:
    types: [closed]
jobs:
  release:
    name: "Release"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Create release"
        uses: "ergebnis/.github/actions/github/release/create@1.8.0"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
